var imgsrc=[
	
	{id:'p1',src:'images/pintu/pintu-img0.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-0.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-1.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-2.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-3.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-4.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-5.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-6.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-7.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0-8.jpg'},
	{id:'p1',src:'images/pintu/pintu-img0.jpg'},
	{id:'p1',src:'images/agin.png'},
	{id:'p1',src:'images/bg.jpg'},
	{id:'p1',src:'images/chakan.png'},
	{id:'p1',src:'images/index-btn.png'},
	{id:'p1',src:'images/loading-he.png'},
	{id:'p1',src:'images/pingyiping.png'},
	{id:'p1',src:'images/pintu-bg.jpg'},
	{id:'p1',src:'images/pintu-time-bg.png'},
	{id:'p1',src:'images/pintu-time-desc.png'},
	{id:'p1',src:'images/pintu-time-tit.png'},
	{id:'p1',src:'images/pintu-time-txt1.png'},
	{id:'p1',src:'images/pintu-time-txt2.png'},
	{id:'p1',src:'images/pintu-time-txt3.png'},
	{id:'p1',src:'images/pintu-tips.png'},
	{id:'p1',src:'images/solon.png'},
	{id:'p1',src:'images/success.png'},
	
]
